//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArturGabdrakhmanov422_DogAndCat.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoDog
    {
        public int Id { get; set; }
        public string PhotoName { get; set; }
        public byte[] PhotoBit { get; set; }
        public Nullable<int> DogId { get; set; }
    
        public virtual Dog Dog { get; set; }
    }
}
